services:
  fastapi-app:
    build: .
    container_name: fastapi-shorturl
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    restart: unless-stopped
